### ISSUE TITLE
Outdated PyPi repository

### ISSUE THREAD

**Issue by Krayfighter** [weegreenblobbie/nsound#21]
trying to install nsound from pypi results in an error asking if `print()` was meant instead of `print` indicating python2 syntax

the exact pip output is as follows

```
  ERROR: Command errored out with exit status 1:
   command: /home/aidenk/Desktop/sound/test/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kv1rtfjj/nsound_9da50de749fa411b8e430f03899bf84e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kv1rtfjj/nsound_9da50de749fa411b8e430f03899bf84e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r00ncwja
       cwd: /tmp/pip-install-kv1rtfjj/nsound_9da50de749fa411b8e430f03899bf84e/
  Complete output (6 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-kv1rtfjj/nsound_9da50de749fa411b8e430f03899bf84e/setup.py", line 88
      print " %s" % tool
      ^^^^^^^^^^^^^^^^^^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/14/72/3bc713b9d3f0c82ae9e177d9f8b368eb2fe5f218373e16b5c2e3585b83a9/Nsound-0.9.4.tar.gz#sha256=4cdb1d052e25b737c1d1d9b1f9d3b9f79807448f94b24e703085e1e604c93bca (from https://pypi.org/simple/nsound/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached Nsound-0.9.3.tar.gz (580 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/aidenk/Desktop/sound/test/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kv1rtfjj/nsound_fe9466d5bfbb4994b40c0efeee83011f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kv1rtfjj/nsound_fe9466d5bfbb4994b40c0efeee83011f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q410sjjt
       cwd: /tmp/pip-install-kv1rtfjj/nsound_fe9466d5bfbb4994b40c0efeee83011f/
  Complete output (6 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-kv1rtfjj/nsound_fe9466d5bfbb4994b40c0efeee83011f/setup.py", line 88
      print " %s" % tool
      ^^^^^^^^^^^^^^^^^^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a1/2d/e806c9f9b641dbf441c109f79516d4eb561e29a45fbcfd5ee0af165078d3/Nsound-0.9.3.tar.gz#sha256=d07a03567d256c0bdf89c0dac4027269feed9516ca717049e530beaa8be120c1 (from https://pypi.org/simple/nsound/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement nsound (from versions: 0.9.3, 0.9.4)
ERROR: No matching distribution found for sound
```

**Comment by weegreenblobbie** [comment]
Thanks for the report, I'll see if I can fix this.

**Comment by weegreenblobbie** [comment]
Try this until I publish to the pypi:

`pip install git+https://github.com/weegreenblobbie/nsound.git@issue-21-fix-pip-install-on-pypi#egg=nsound`

**Comment by weegreenblobbie** [comment]
I've merged changes to trunk, will publish to pypi soonish.

**Comment by weegreenblobbie** [comment]
Release 0.9.5 has been published to pypi: https://pypi.org/project/Nsound/0.9.5/
